name: E2E tests

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run E2E script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          MP_ACCESS_TOKEN: ${{ secrets.MP_ACCESS_TOKEN }}
        run: |
          node ./scripts/e2e_test.js
